export const BUE_PORTFOLIO_ITEM = 'BUE_PORTFOLIO_ITEM';
export const SELL_PORTFOLIO_ITEM = 'SELL_PORTFOLIO_ITEM';
export const SET_PORTFOLIO_STOCK = 'SET_PORTFOLIO_STOCK';
export const SET_PORTFOLIO_HISTORY = 'SET_PORTFOLIO_HISTORY';
export const SET_PORTFOLIO_COUNT = 'SET_PORTFOLIO_COUNT';
export const FETCH_PORTFOLIO = 'FETCH_PORTFOLIO';

export default {
  BUE_PORTFOLIO_ITEM,
  SELL_PORTFOLIO_ITEM,
  SET_PORTFOLIO_STOCK,
  SET_PORTFOLIO_HISTORY,
  SET_PORTFOLIO_COUNT,
  FETCH_PORTFOLIO,
}
